### PR TITLE
updated dependencies to latest version

### LINKED ISSUE #83: Old httpclient version makes this plugin incompatible with other plugins who already use the newer version.
Please update your httpclient version

### PR DESCRIPTION
**Pull request by Azim-D3Tm**
Fixes #83

### CODE REVIEW

**Comment by r-clancy** [comment]
Thanks!

**Comment by Azim-D3Tm** [comment]
When you gonna release the next version with fixes?

**Comment by r-clancy** [comment]
@Azim-D3Tm I can release a new version tonight.

**Comment by LucianDevran** [comment]
perfect timing XD

**Comment by Azim-D3Tm** [comment]
@r-clancy that would be nice, thanks.

**Pull request merged**
